### ISSUE TITLE
Maps dont line up in item frames

### ISSUE THREAD

**Issue by TheHappyHopper** [zDevelopers/ImageOnMap#150] opened 2021-02-25 07:00 UTC
Maps arent lining up in item frames and are giving incorrect scaling, making the plugin unusable.
There are no errors in console  running yatopia 1.16.5 build 33

Attached is screenshot, placed maps have random rotations when placed individually, turns it into a puzzle of sorts
left is automatic map, right is manually done.
![2021-02-24_22 58 22](https://user-images.githubusercontent.com/66880702/109115544-13ba3400-76f4-11eb-8365-7cda35e604c0.png)

**Comment by AmauryCarrade** [comment] 2021-02-25 09:12
Are these reused item frames? They keep their internal rotation, that could be the cause

**Comment by TheHappyHopper** [comment] 2021-02-25 21:41
> Are these reused item frames? They keep their internal rotation, that could be the cause

No, these are fresh item frames placed just for this

**Comment by Vlammar** [comment] 2021-02-25 22:52
This look a lot like #86 It seams this is a duplicate.

**Comment by AmauryCarrade** [comment] 2021-04-04 12:22
Closing as a duplicate of #86. We keep only one issue per problem, but thanks for your report!

**Closed as completed by AmauryCarrade** 2021-04-04 12:22 UTC
Labels: Duplicate
