### ISSUE TITLE
Splatter Maps Not Working

### ISSUE THREAD

**Issue by cqm3ron** [zDevelopers/ImageOnMap#208] opened 2021-08-05 16:35 UTC
I use a splatter map on an item frame as said in the lore of the item (in the bottom-right frame), I have the right amount of item frames, and this happens:
![image](https://user-images.githubusercontent.com/73529986/128387301-17ddc828-62ab-4b4e-ad30-ad2d632c2c03.png)
For reference, the link to the original image is:
https://crafthead.net/helm/DaCringyLemon
I'm running a PaperMC server with these plugins:
![image](https://user-images.githubusercontent.com/73529986/128387381-57909c97-4534-4ba4-9159-24007eafd74b.png)
Help appreciated :)

**Comment by AmauryCarrade** [comment] 2021-08-05 21:37
Hello, what's your server version? Is Paper up to date?

**Comment by cqm3ron** [comment] 2021-08-06 07:46
I'm running 1.17.1, and  Paper-1.17.1-157.jar, the latest version

**Comment by Vlammar** [comment] 2021-08-06 07:50
Duplicate of https://github.com/zDevelopers/ImageOnMap/issues/195

**Closed as completed by Vlammar** 2021-08-06 07:50 UTC
Labels: Duplicate
