### ISSUE TITLE
ImageOnMap abruptly stopped working

### ISSUE THREAD

**Issue by karlovm** [zDevelopers/ImageOnMap#89] opened 2020-06-03 09:56 UTC
I use ImageOnMap on 1.15.2 4.0 (2) and players could create maps, but now they cant.
If you try to make a new map, it successfully works, but if you try to place it, you will the the message: size 20x12 (but map says the size is 2x2 or any another size). And if I have 20x12 blocks map can't place.

Sorry for my english.
![image](https://user-images.githubusercontent.com/51130679/83623131-99f87e00-a599-11ea-9428-7371e34c38ff.png)
![image](https://user-images.githubusercontent.com/51130679/83623150-a086f580-a599-11ea-85ec-90e158fd695e.png)
![image](https://user-images.githubusercontent.com/51130679/83623168-a67cd680-a599-11ea-862d-1e2701e468de.png)

**Comment by karlovm** [comment] 2020-06-03 09:58
It works for all maps now. Old maps work

**Comment by karlovm** [comment] 2020-06-03 10:00
Oh, sorry, I have only 19 blocks instead 20. Now I see something strange with maps already created
![image](https://user-images.githubusercontent.com/51130679/83623615-37ec4880-a59a-11ea-8e82-9f0583e04260.png)

**Comment by Vlammar** [comment] 2020-06-03 16:37
Duplicate of https://github.com/zDevelopers/ImageOnMap/issues/86 
Did you use /map delete ?

**Comment by karlovm** [comment] 2020-06-04 05:43
ZIP with all in maps folder
https://yadi.sk/d/jL2zhJSv5AuEHg

**Comment by karlovm** [comment] 2020-06-04 06:18
Players can't create a map. Please fix

**Comment by karlovm** [comment] 2020-06-04 11:10
Players say that they can create maps only 1x1

**Closed** 2021-01-16 00:39 UTC
Labels: Duplicate
