### ISSUE TITLE
Renaming a map causes inventory loss

### ISSUE THREAD

**Issue by kaanakduman** [zDevelopers/ImageOnMap#110] opened 2020-07-06 07:12 UTC
I'm on Purpur-635 for 1.16.1. I'm using ImageOnMap v4.0
Here is a video on how to reproduce the issue:
https://imgur.com/a/RgX2eV3

**Comment by AmauryCarrade** [comment] 2020-07-06 10:48
Hi and thanks for this report! I _think_ I see what the cause can be, but do you have an error, an exception, or something, in your console, either when opening or closing the sign, or when you interact with an inventory after that?

**Comment by Vlammar** [comment] 2020-08-03 12:11
I digged, it seems to be caused by the prompt (sign). after renaming you should have to leave 2 inventories (the map selection and the map part selection) but you only have to leave the map part selection. The plugin then thinks that you are still in the map selection one and replace item in inventory.

**Comment by Vlammar** [comment] 2021-01-16 00:36
Fixed by #137 will be added in next update, thanks for the report :)

**Closed as completed by Vlammar** 2021-01-16 00:36 UTC
Labels: Bug, Critical
