### ISSUE TITLE
Image duping bug

### ISSUE THREAD

**Issue by WoefieProCoder** [zDevelopers/ImageOnMap#213] opened 2021-09-11 23:33 UTC
You can dupe maps with images on them. (How is shown in the video)

https://user-images.githubusercontent.com/81086124/132965969-2c59d87b-1c1c-4a22-ae0b-9dd8583bb083.mp4

**Comment by Vlammar** [comment] 2021-11-17 22:16
Duplicate of #202

**Closed as completed by Vlammar** 2021-11-17 22:16 UTC
Labels: Duplicate
