### ISSUE TITLE
Non-opped player executing "/maptool list" in 1.16.5 causes null pointer exception in the game log

### ISSUE THREAD

**Issue by Grossley** [zDevelopers/ImageOnMap#171] opened 2021-04-19 15:36 UTC
```
[07:36:49] [Server thread/INFO]: PLAYER issued server command: /maptool list
[07:36:50] [Server thread/WARN]: [ImageOnMap] Task #354 for ImageOnMap v4.1.2 generated an exception
java.lang.NullPointerException: null
at fr.moribus.imageonmap.map.PlayerMapStore.load(PlayerMapStore.java:255) ~[?:?]
at fr.moribus.imageonmap.map.MapManager.getPlayerMapStore(MapManager.java:359) ~[?:?]
at fr.moribus.imageonmap.map.MapManager.getMapList(MapManager.java:169) ~[?:?]
at fr.moribus.imageonmap.commands.maptool.ListCommand.lambda$run$0(ListCommand.java:83) ~[?:?]
at fr.zcraft.imageonmap.quartzlib.components.commands.CommandWorkers$1.finished(CommandWorkers.java:23) ~[?:?]
at fr.zcraft.imageonmap.quartzlib.components.commands.CommandWorkers$1.finished(CommandWorkers.java:20) ~[?:?]
at fr.zcraft.imageonmap.quartzlib.components.worker.WorkerCallbackManager$WorkerRunnableInfo.runCallback(WorkerCallbackManager.java:126) ~[?:?]
at fr.zcraft.imageonmap.quartzlib.components.worker.WorkerCallbackManager.run(WorkerCallbackManager.java:105) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[minecraft_server.jar:git-Paper-602]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[minecraft_server.jar:git-Paper-602]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[minecraft_server.jar:git-Paper-602]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[minecraft_server.jar:git-Paper-602]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[minecraft_server.jar:git-Paper-602]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[minecraft_server.jar:git-Paper-602]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[minecraft_server.jar:git-Paper-602]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Vlammar** [comment] 2021-05-30 14:24
This issue seems to be a duplicate of #172 . I tried to reproduce it without success but i'm pretty sure that's the same cause of error

**Closed as completed by Vlammar** 2021-05-30 14:24 UTC
Labels: Bug, Cannot reproduce
