### ISSUE TITLE
"Rendering" text stays on screen when map render fails

### ISSUE THREAD

**Issue by James76931** [zDevelopers/ImageOnMap#75] opened 2020-03-18 20:49 UTC
Hi.

When the map rendering fails due to a user meeting their map quota ("You have too many maps...") the green "Rendering..." text above the hotbar does not disappear.

![](https://cdn.discordapp.com/attachments/372503236088823808/689938305332019257/unknown.png)

**Comment by Vlammar** [comment] 2020-03-18 22:33
Duplicate of https://github.com/zDevelopers/ImageOnMap/issues/71
We are aware of this issue, I don't plan to fix it for 4.0, that will be the case for 4.1

**Closed** 2020-03-18 23:39 UTC
Labels: Bug, Duplicate
