### ISSUE TITLE
[Bug] Map Management Not Working

### ISSUE THREAD

**Issue by ELPOZ** [zDevelopers/ImageOnMap#156] opened 2021-04-09 01:59 UTC
I've encountered a problem with the map management system: the "/maps" and "/maptool explore" commands both do not work. I am using this plugin alongside EssentialsX 2.19.0, LuckyPerms 5.3.17, and Vault on a Paper build#556 1.16.5 server. This is the error I receive in the console when using /maps:

[21:46:50 WARN]: Task #70851 for ImageOnMap v4.0 generated an exception
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.scriptEngine" is null
	at fr.moribus.imageonmap.components.i18n.translators.gettext.GettextPOTranslator.getPluralIndex(GettextPOTranslator.java:104) ~[?:?]
	at fr.moribus.imageonmap.components.i18n.translators.Translator.translate(Translator.java:186) ~[?:?]
	at fr.moribus.imageonmap.components.i18n.I18n.translateFromChain(I18n.java:452) ~[?:?]
	at fr.moribus.imageonmap.components.i18n.I18n.translate(I18n.java:499) ~[?:?]
	at fr.moribus.imageonmap.components.i18n.I.tn(I.java:353) ~[?:?]
	at fr.moribus.imageonmap.gui.MapListGui.onUpdate(MapListGui.java:189) ~[?:?]
	at fr.moribus.imageonmap.components.gui.GuiBase.update(GuiBase.java:80) ~[?:?]
	at fr.moribus.imageonmap.components.gui.InventoryGui.update(InventoryGui.java:185) ~[?:?]
	at fr.moribus.imageonmap.components.gui.ActionGui.update(ActionGui.java:299) ~[?:?]
	at fr.moribus.imageonmap.components.gui.GuiBase.open(GuiBase.java:140) ~[?:?]
	at fr.moribus.imageonmap.components.gui.InventoryGui.open(InventoryGui.java:111) ~[?:?]
	at fr.moribus.imageonmap.components.gui.Gui$1.run(Gui.java:112) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-558]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-558]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-558]
	at java.lang.Thread.run(Thread.java:831) [?:?]

I've tried fresh installs of the plugin and regenerating the config file as well as running it without any other plugins but nothing has worked.

**Comment by Vlammar** [comment] 2021-04-09 06:42
The issue is with the nashor engine. You may be running java 15 or newer and they removed it. A fix is planned for the issue with minehut (they blocked JS engines).

**Comment by Vlammar** [comment] 2021-04-19 21:46
Fixed with the 4.1.2

**Closed as completed by Vlammar** 2021-04-19 21:46 UTC
