### ISSUE TITLE
issues with 1x1 maps with troubleshooting

### ISSUE THREAD

**Issue by kuraiskrap** [zDevelopers/ImageOnMap#193] opened 2021-06-13 22:54 UTC
when you place a map, it consumes 2 maps, if your only holding one it fails to place.
splatter maps are ok, effects standalone maps or single parts of splattermaps
does not effect maps if placed from off hand
does not effect normal in game maps only image to map
does not effect players in creative, **only in survival**, i think this could be why it wasnt able to be reproduced?

rolled back from 4.1.2
continued in 4.1.1
4.1 used 2 maps still, but wouldnt delete a placed map when you only held one
4.0 works fine
using java 11
server is behind waterfall (bungeecord)
tried removing every plugin besides essentials
useing paper, tried a 153 86 old version and current version
and the panel is pyrodactyl

if you want access to a server its happening to for troubleshooting
i offer my test server, can give you access to the web console

**Comment by AmauryCarrade** [comment] 2021-06-22 12:16
Thanks for this detailed walk-through! What is your Minecraft version and server platform (Spigot, Paper, …)? The server itself, not the Bungeecord network

**Comment by kuraiskrap** [comment] 2021-06-22 14:23
honestly im like wow i forgot to mention we are using **1.16.5** out of everything i wrote down
and we are using **paper** its mentioned in the above post
and just to correct the last post, we are actually using **waterfall** for bungeecord in case thats somehow related

**Comment by AmauryCarrade** [comment] 2021-06-22 14:43
Thanks! We _may_ know the cause, we'ill investigate when possible :) .

**Comment by Vlammar** [comment] 2021-12-13 15:28
Fixed in 4.2.1. This issue might be there since a long time, or something changed on spigot/paper/minecraft side that we are not aware of. See https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.2.1

**Closed as completed by Vlammar** 2021-12-13 15:28 UTC
Labels: Bug, Spigot/Paper weirdness
