### ISSUE TITLE
Image Size Does Not Work

### ISSUE THREAD

**Issue by boyandres** [zDevelopers/ImageOnMap#153] opened 2021-03-25 12:59 UTC
I have a problem, what happens is that my server is hosted by others, and the problem is that when I put the command / tomap and the exact size to put in the item frame, and it gives me a size 10x7 and when I put the image with that size I get the image badly cropped and my previous images
![image](https://user-images.githubusercontent.com/80431674/112476602-d7a8dc00-8d50-11eb-8b44-daef293dca9e.png)

**Comment by HandedWasTaken** [comment] 2021-03-25 13:02
It also happens to me like the 73#

**Comment by HandedWasTaken** [comment] 2021-03-25 13:02
It also happens to me like the #73

**Comment by boyandres** [comment] 2021-03-25 13:03
It also happens to me like the #150

**Comment by AmauryCarrade** [comment] 2021-04-04 12:20
For temporary fix on your side, [please see this new FAQ entry](https://dev.zcraft.fr/imageonmap/faq/#imageonmap-say-there-is-not-enough-place-for-a-splatter-map-but-there-is-and-the-required-size-is-not-consistant).

Closing as a duplicate of #86 (we keep only one issue per problem, but thanks for the report!).

**Closed as completed by AmauryCarrade** 2021-04-04 12:20 UTC
Labels: Bug, Duplicate, Critical
